-- MySQL Script generated by MySQL Workbench
-- jue 18 ago 2022 18:08:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Backend_Developer_Test
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Backend_Developer_Test` ;

-- -----------------------------------------------------
-- Schema Backend_Developer_Test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Backend_Developer_Test` ;
USE `Backend_Developer_Test` ;

-- -----------------------------------------------------
-- Table `Backend_Developer_Test`.`Autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Backend_Developer_Test`.`Autor` ;

CREATE TABLE IF NOT EXISTS `Backend_Developer_Test`.`Autor` (
  `Nombre` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NULL,
  PRIMARY KEY (`Nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Backend_Developer_Test`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Backend_Developer_Test`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `Backend_Developer_Test`.`Usuario` (
  `Nombre` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NULL,
  `Telefono` INT NULL,
  `Password` VARCHAR(45) NULL,
  `Autores_Nombre` VARCHAR(45) NOT NULL,
  `Autor_Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nombre`, `Autores_Nombre`),
  INDEX `fk_Usuario_Autor1_idx` (`Autor_Nombre` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Autor1`
    FOREIGN KEY (`Autor_Nombre`)
    REFERENCES `Backend_Developer_Test`.`Autor` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Backend_Developer_Test`.`Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Backend_Developer_Test`.`Categoria` ;

CREATE TABLE IF NOT EXISTS `Backend_Developer_Test`.`Categoria` (
  `Nombre` VARCHAR(45) NOT NULL,
  `Imagen` BLOB NULL,
  PRIMARY KEY (`Nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Backend_Developer_Test`.`Post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Backend_Developer_Test`.`Post` ;

CREATE TABLE IF NOT EXISTS `Backend_Developer_Test`.`Post` (
  `Titulo` VARCHAR(45) NOT NULL,
  `Autor` VARCHAR(45) NULL,
  `DescripcionGrafica` VARCHAR(45) NULL,
  `Contenido` VARCHAR(45) NULL,
  `Imagen` BLOB NULL,
  `Categoria` VARCHAR(45) NULL,
  `FechaPublicacion` DATE NULL,
  `Usuario` VARCHAR(45) NOT NULL,
  `Usuario_Nombre` VARCHAR(45) NOT NULL,
  `Usuario_Autores_Nombre` VARCHAR(45) NOT NULL,
  `Usuario_Nombre1` VARCHAR(45) NOT NULL,
  `Usuario_Autores_Nombre1` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Titulo`),
  INDEX `fk_Post_Usuario1_idx` (`Usuario_Nombre1` ASC, `Usuario_Autores_Nombre1` ASC) VISIBLE,
  CONSTRAINT `fk_Post_Usuario1`
    FOREIGN KEY (`Usuario_Nombre1` , `Usuario_Autores_Nombre1`)
    REFERENCES `Backend_Developer_Test`.`Usuario` (`Nombre` , `Autores_Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Backend_Developer_Test`.`Post_has_Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Backend_Developer_Test`.`Post_has_Categoria` ;

CREATE TABLE IF NOT EXISTS `Backend_Developer_Test`.`Post_has_Categoria` (
  `Post_Titulo` VARCHAR(45) NOT NULL,
  `Categoria_Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Post_Titulo`, `Categoria_Nombre`),
  INDEX `fk_Post_has_Categoria_Categoria1_idx` (`Categoria_Nombre` ASC) VISIBLE,
  INDEX `fk_Post_has_Categoria_Post1_idx` (`Post_Titulo` ASC) VISIBLE,
  CONSTRAINT `fk_Post_has_Categoria_Post1`
    FOREIGN KEY (`Post_Titulo`)
    REFERENCES `Backend_Developer_Test`.`Post` (`Titulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Post_has_Categoria_Categoria1`
    FOREIGN KEY (`Categoria_Nombre`)
    REFERENCES `Backend_Developer_Test`.`Categoria` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
